---
title: "Server Configuration"
---

Configuring useful features on your server.

### Transcoding

When streaming content, sometimes transcoding will be required to reduce buffering and increase compatiblity.  For example, if the upload speed of your internet low, the media must be transcoded to prevent buffering.  Additionally, some devices don't support certain codecs (eg. H.265, AV1, etc) and require media to be transcoded for compatiblity.

Within Jellyfin, there are many settings for transcoding, but here, I will focus on hardware acceleration, format options, and how far ahead of a given timestamp the server will transcode.

#### Hardware Acceleration



#### Format Options



#### Buffer

When transcoding, the server will buffer a certain amount of content ahead of the current playback position.  This allows for smoother playback, especially on slower connections.  The default setting is 180 seconds, which is generally sufficient for most users.  However, if you experience buffering, you may want to increase this value.  Conversely, if you have a fast connection and want to reduce the amount of data being buffered, you can decrease this value.

The server will also hold onto a period of media after it's been played on the client, allowing for quick rewinding without needing to re-transcode.  If you have a fast connection or will infrequently rewind content, you can decrease this value.

### Trickplay



### Scheduled Tasks

Scheduled tasks allow your server to run certain operations automatically, keeping the server optimized and metadata up to date.  Tasks can be set to run daily, weekly, after a certain time interval, and/or every time the server starts up.  Additionally, a time limit can be set on the tasks to prevent them from running too long.

On my server, I have every scheduled task set to run daily at 1:00am, allowing them to run and finish while I'm very unlikely to be using the server.  Nearly all of the tasks run in less than a minute, so running them weekly would likely be just fine, although the longer you go without running the tasks, the longer they may take.

My recommendation is to start by setting all the tasks to run weekly in the early-morning and adjust from there.

### Plugins

Jellyfin comes with the ability to install plugins, with nearly 40 able to be easily installed within the server settings.  These allow you to pull metadata from more sources, download subtitles from the internet, and have more administrative tools.

To install a plugin, simply click the plugin you want to install, click install, and restart your server.  To uninstall, click on the installed plugin, click uninstall, and restart your server.

### Other Useful Configuration

