---
title: "Demo"
---

Here is an interactive demo of what your server can look like!

```{=html}
<iframe width="780" height="500" src="https://stream.bandguymichael.org" title="Quarto Documentation"></iframe>
```

Attributions for content used:

*Big Buck Bunny* &copy; copyright 2008, Blender Foundation / www.bigbuckbunny.org

*Code Rush* &copy; copyright 2000, David Winton / https://makertube.net/w/iNHBzq7vYn8Mkw82z6yNcs

"Anachronist", "Autumn Day", "Bathed in the Light", "Brightly Fancy", "Calmant", "Carefree", "Clean Soul", "Crunk Knight", "Danse Morialta", "Dream Culture", "Enchanted Journey", "First Call", "Fluffing a Duck", "Hamster March", "Home Base Groove", "Impact Allegretto", "Impact Andante", "Impact Intermezzo", "Impact Lento", "Impact Moderato", "Impact Prelude", "Impromptu in Quarter Comma Meantone", "Inner Light", "Lift Motif", "Meditation Impromptu 01", "Meditation Impromptu 02", "Meditation Impromptu 03", "Narcissus", "Nothing Broken", "On the Passing of Time", "Petulant March", "Plain Loafer", "Radio Martini", "Reaching Out", "Resignation", "Silver Blue Light", "Sinfonia No. 3 in D Major - BWV 789", "Sing Along with Jim", "Smoother Move", "Sovereign Quarter", "Tranquility", "Ujangong Mix", "Vintage Education", "Windswept", "Winner Winner!", "Winter Reflections"; Kevin MacLeod (incompetech.com); Licensed under Creative Commons: By Attribution 4.0; http://creativecommons.org/licenses/by/4.0/